[build]
  command = "npm run build"
  publish = "dist/public"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/workbox-*.js"
  [headers.values]
    Cache-Control = "no-cache"
